<select name="regions" class="flat">
	<option value="213">Москва</option>
	<option value="149">Беларусь</option>
	<option value="225">Россия</option>
	<option value="0">По-умолчанию</option>
	<option value="0">------------</option>
	<option value="138">Австралия и Океания</option>
	<option value="183">Азия</option>
	<option value="11235">Алтайский край</option>
	<option value="20">Архангельск</option>
	<option value="10842">Архангельская область</option>
	<option value="241">Африка</option>
	<option value="11111">Башкортостан</option>
	<option value="24">Великий Новгород</option>
	<option value="75">Владивосток</option>
	<option value="21">Вологда</option>
	<option value="10853">Вологодская область</option>
	<option value="73">Дальний Восток</option>
	<option value="111">Европа</option>
	<option value="54">Екатеринбург</option>
	<option value="44">Ижевск</option>
	<option value="63">Иркутск</option>
	<option value="22">Калининград</option>
	<option value="10857">Калининградская область</option>
	<option value="62">Красноярск</option>
	<option value="11309">Красноярский край</option>
	<option value="1">Москва и Московская область</option>
	<option value="157">Минск</option>
	<option value="29630">Минская область</option>
	<option value="23">Мурманск</option>
	<option value="10897">Мурманская область</option>
	<option value="47">Нижний Новгород</option>
	<option value="10904">Новгородская область</option>
	<option value="65">Новосибирск</option>
	<option value="11316">Новосибирская область</option>
	<option value="48">Оренбург</option>
	<option value="50">Пермь</option>
	<option value="11108">Пермский край</option>
	<option value="25">Псков</option>
	<option value="10926">Псковская область</option>
	<option value="10231">Республика Алтай</option>
	<option value="225">Россия</option>
	<option value="10838">Ростов</option>
	<option value="39">Ростов-на-Дону</option>
	<option value="11029">Ростовская область</option>
	<option value="51">Самара</option>
	<option value="2">Санкт-Петербург</option>
	<option value="10174">Санкт-Петербург и Ленинградская область</option>
	<option value="10002">Северная Америка</option>
	<option value="59">Сибирь</option>
	<option value="166">СНГ</option>
	<option value="14">Тверь</option>
	<option value="10819">Тверская область</option>
	<option value="15">Тула</option>
	<option value="10832">Тульская область</option>
	<option value="55">Тюмень</option>
	<option value="187">Украина</option>
	<option value="195">Ульяновск</option>
	<option value="11153">Ульяновская область</option>
	<option value="147">Харьков</option>
	<option value="56">Челябинск</option>
	<option value="10003">Южная Америка</option>
</select>