{component_button:package_name=page::page_composer;label=main;page=./index.html;size=100;icon=home_064.gif;permit=admin}
{component_button:package_name=core::package_manager;label=package_manager;page=./package_manager.html;size=100;icon=packages_064.gif;permit=package_manager}
{component_button:package_name=page::page_manager;label=page_manager;page=./page_manager.html;size=100;icon=page_064.gif;permit=page_manager}
{component_button:package_name=user::user_view;label=user_manager_label;page=./user_manager.html;size=100;icon=users_064.gif;permit=user_manager}
{component_button:package_name=permit;label=permits_label;page=./permit_manager.html;size=100;icon=permits_064.gif;permit=permit_manager}
{component_button:package_name=permit;label=groups_label;page=./group_manager.html;size=100;icon=groups_064.gif;permit=group_manager}
{component_button:package_name=permit;label=user_permits_label;page=./user_permit_manager.html;size=100;icon=user_permits_064.gif;permit=permit_manager}
{component_button:package_name=system_structure;label=system_structure_label;page=./system_structure_manager.html;size=100;icon=system_structure_064.gif;permit=system_structure_manager}
{component_button:package_name=ad::ad_campaign::ad_campaign_manager;label=ad_campaign_manager;page=./ad_campaign_manager.html;size=100;icon=ad_campaign_064.gif;permit=ad_campaign_manager}
{component_button:package_name=ad::ad_banner::ad_banner_manager;label=ad_banner_manager;page=./ad_banner_manager.html;size=100;icon=ad_banner_064.gif;permit=ad_banner_manager}
{component_button:package_name=content::content_view;label=content_manager;page=./content_manager.html;size=100;icon=content_064.gif;permit=content_manager}
{component_button:package_name=content::content_view;label=news_manager;page=./news_manager.html;size=100;icon=news_064.gif;permit=news_manager}
{component_button:package_name=content::content_view;label=article_manager;page=./article_manager.html;size=100;icon=article_064.gif;permit=article_manager}
{component_button:package_name=content::content_view;label=faq_manager;page=./faq_manager.html;size=100;icon=faq_064.gif;permit=faq_manager}
{component_button:package_name=content::content_view;label=blog_manager;page=./blog_manager.html;size=100;icon=blog_064.gif;permit=blog_manager}
{component_button:package_name=comment::comment_view;label=comment_manager_label;page=./comment_manager.html;size=100;icon=comment_064.gif;permit=comment_manager}
{component_button:package_name=review::review_view;label=review_manager_label;page=./review_manager.html;size=100;icon=review_064.gif;permit=review_manager}
{component_button:package_name=site::site_view;label=site_manager;page=./site_manager.html;size=100;icon=site_064.gif;permit=site_manager}
{component_button:package_name=settings::settings_view;label=system_settings_label;page=./system_settings.html;size=100;icon=settings_064.gif;permit=admin}
{component_button:package_name=category::category_view;label=category_label;page=./category_manager.html;size=100;icon=category_064.gif;permit=category_manager}
{component_button:package_name=category::category_view;label=category_label;page=./tree_category_manager.html?direct_category_name[eq]content_category;size=100;icon=tree_category_064.gif;permit=category_manager}
{component_button:package_name=pmsg::pmsg_view;label=pmsg;page=./pmsg.html;size=100;icon=message{if:condition={not_read_messages_count};then=_new}_064.gif;permit=registered}
{component_button:package_name=database::dump;label=database_manager;page=./database_manager.html;size=100;icon=database_064.gif;permit=database_manager}
{switch_user_button}
{logout_img_button}
{lang_file:package_name=permit}
{lang_file:package_name=system_structure}